build and push image:
  image: docker:19.03.6
  stage: build
  only:
    - tags
  services:
    - name: docker:19.03.6-dind
      command: [ "--experimental" ]
  variables:
#    DOCKER_HOST: tcp://docker:2375 # free gitlab runner
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
    DOCKER_CLI_EXPERIMENTAL: enabled
    BUILDX_URL: https://github.com/docker/buildx/releases/download/v0.4.2/buildx-v0.4.2.linux-amd64
    BUILDX_BUILDER: multistageBuilder
    BUILDX_PLATFORM: linux/amd64,linux/arm64,linux/arm/v7
  before_script:
    - mkdir -p $HOME/.docker/cli-plugins/
    - wget -O $HOME/.docker/cli-plugins/docker-buildx $BUILDX_URL
    - chmod a+x $HOME/.docker/cli-plugins/docker-buildx
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use --driver docker-container --name ${BUILDX_BUILDER} --platform=${BUILDX_PLATFORM}
    - docker buildx inspect --bootstrap ${BUILDX_BUILDER}
    - docker buildx ls
    - echo $DOCKER_REGISTRY_PASSWORD | docker login --username "${DOCKER_REGISTRY_USER}" --password-stdin ${DOCKER_REGISTRY}
  script:
    - docker buildx build --no-cache --target=production -t knobik/shelly-plug-influxdb:latest -t knobik/shelly-plug-influxdb:${CI_COMMIT_TAG} --platform=${BUILDX_PLATFORM} --push "."

