version: '3.4'
services:
  shelly-plug-influxdb:
    build:
      context: .
      dockerfile: Dockerfile
#    environment:
#      USER_UID: ${USER_UID:-1000}
#      USER_GID: ${USER_GID:-1000}
    volumes:
      - ./:./app